Fix rpslparse()'s prototype when using a newer toolchain
Compilation with a fairly new (Debian jessie) toolchain fails with:

../.libs/libirrtoolset.a(object.o): In function `Object::parse()':
/root/paravoid/irrtoolset/irrtoolset-5.0.1/src/rpsl/object.cc:131:
undefined reference to `rpslparse(void*)'

Fix this by adjusting for the new prototype, which doesn't need any
arguments.